name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check for composer.json
      id: composer
      run: |
        if [ -f composer.json ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Setup PHP with Composer
      if: steps.composer.outputs.exists == 'true'
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: composer
        coverage: none

    - name: Validate composer.json and composer.lock
      if: steps.composer.outputs.exists == 'true'
      run: composer validate --strict

    - name: Cache Composer packages
      if: steps.composer.outputs.exists == 'true'
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      if: steps.composer.outputs.exists == 'true'
      run: composer install --prefer-dist --no-progress --no-suggest --no-interaction --no-ansi

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   if: steps.composer.outputs.exists == 'true'
    #   run: composer run-script test
